apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ml-prediction-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: ml.prediction.vbo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ml-prediction
                port:
                  number: 8000